USE [CMS]
GO

/****** Object:  Table [dbo].[LMDB_struct_log]    Script Date: 03/29/2012 13:51:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LMDB_STRUCT_LOG](
	[nid] [int] IDENTITY(1,1) NOT NULL,
	[DATETIME] [datetime] NULL,
	[DBNM] [nvarchar](max) NULL,
	[DBCONTENT] [nvarchar](max) NULL,
	[STATUS] [varchar](1) NULL,
	[USERID] [varchar](50) NULL,
 CONSTRAINT [pk_LMDB_STRUCT_LOG] PRIMARY KEY CLUSTERED 
(
	[nid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


