//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.42。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="FaxServiceSOAP11Binding", Namespace="http://axis2.fax.uniproud.com")]
public partial class FaxService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback QueryResultForRecvTaskZipOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteFileForRecvTaskOperationCompleted;
    
    private System.Threading.SendOrPostCallback AddUserInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback ChangePasswordOperationCompleted;
    
    private System.Threading.SendOrPostCallback QueryResultForSendTaskOperationCompleted;
    
    private System.Threading.SendOrPostCallback QueryResultForRecvTaskOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendPHFaxToServerOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendFaxToServerOperationCompleted;
    
    private System.Threading.SendOrPostCallback ModifyDeptInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback AddDeptInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback ModifyUserInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetUserInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteFileForSendTaskOperationCompleted;
    
    /// <remarks/>
    public FaxService() {
        this.Url = "http://222.66.124.119/servlet/services/FaxService";
        //this.Url = "http://www.35fax.net/services/FaxService";
        //this.Url = "http://222.66.124.119/services/FaxService";
    }
    
    /// <remarks/>
    public event QueryResultForRecvTaskZipCompletedEventHandler QueryResultForRecvTaskZipCompleted;
    
    /// <remarks/>
    public event DeleteFileForRecvTaskCompletedEventHandler DeleteFileForRecvTaskCompleted;
    
    /// <remarks/>
    public event AddUserInfoCompletedEventHandler AddUserInfoCompleted;
    
    /// <remarks/>
    public event ChangePasswordCompletedEventHandler ChangePasswordCompleted;
    
    /// <remarks/>
    public event QueryResultForSendTaskCompletedEventHandler QueryResultForSendTaskCompleted;
    
    /// <remarks/>
    public event QueryResultForRecvTaskCompletedEventHandler QueryResultForRecvTaskCompleted;
    
    /// <remarks/>
    public event SendPHFaxToServerCompletedEventHandler SendPHFaxToServerCompleted;
    
    /// <remarks/>
    public event SendFaxToServerCompletedEventHandler SendFaxToServerCompleted;
    
    /// <remarks/>
    public event ModifyDeptInfoCompletedEventHandler ModifyDeptInfoCompleted;
    
    /// <remarks/>
    public event AddDeptInfoCompletedEventHandler AddDeptInfoCompleted;
    
    /// <remarks/>
    public event ModifyUserInfoCompletedEventHandler ModifyUserInfoCompleted;
    
    /// <remarks/>
    public event GetUserInfoCompletedEventHandler GetUserInfoCompleted;
    
    /// <remarks/>
    public event DeleteFileForSendTaskCompletedEventHandler DeleteFileForSendTaskCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:QueryResultForRecvTaskZip", RequestNamespace="http://axis2.fax.uniproud.com", ResponseNamespace="http://axis2.fax.uniproud.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public string QueryResultForRecvTaskZip([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string qrForRTZStr) {
        object[] results = this.Invoke("QueryResultForRecvTaskZip", new object[] {
                    qrForRTZStr});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginQueryResultForRecvTaskZip(string qrForRTZStr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("QueryResultForRecvTaskZip", new object[] {
                    qrForRTZStr}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndQueryResultForRecvTaskZip(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void QueryResultForRecvTaskZipAsync(string qrForRTZStr) {
        this.QueryResultForRecvTaskZipAsync(qrForRTZStr, null);
    }
    
    /// <remarks/>
    public void QueryResultForRecvTaskZipAsync(string qrForRTZStr, object userState) {
        if ((this.QueryResultForRecvTaskZipOperationCompleted == null)) {
            this.QueryResultForRecvTaskZipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryResultForRecvTaskZipOperationCompleted);
        }
        this.InvokeAsync("QueryResultForRecvTaskZip", new object[] {
                    qrForRTZStr}, this.QueryResultForRecvTaskZipOperationCompleted, userState);
    }
    
    private void OnQueryResultForRecvTaskZipOperationCompleted(object arg) {
        if ((this.QueryResultForRecvTaskZipCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.QueryResultForRecvTaskZipCompleted(this, new QueryResultForRecvTaskZipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:DeleteFileForRecvTask", RequestNamespace="http://axis2.fax.uniproud.com", ResponseNamespace="http://axis2.fax.uniproud.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public string DeleteFileForRecvTask([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string delForRTStr) {
        object[] results = this.Invoke("DeleteFileForRecvTask", new object[] {
                    delForRTStr});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteFileForRecvTask(string delForRTStr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteFileForRecvTask", new object[] {
                    delForRTStr}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndDeleteFileForRecvTask(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void DeleteFileForRecvTaskAsync(string delForRTStr) {
        this.DeleteFileForRecvTaskAsync(delForRTStr, null);
    }
    
    /// <remarks/>
    public void DeleteFileForRecvTaskAsync(string delForRTStr, object userState) {
        if ((this.DeleteFileForRecvTaskOperationCompleted == null)) {
            this.DeleteFileForRecvTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFileForRecvTaskOperationCompleted);
        }
        this.InvokeAsync("DeleteFileForRecvTask", new object[] {
                    delForRTStr}, this.DeleteFileForRecvTaskOperationCompleted, userState);
    }
    
    private void OnDeleteFileForRecvTaskOperationCompleted(object arg) {
        if ((this.DeleteFileForRecvTaskCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteFileForRecvTaskCompleted(this, new DeleteFileForRecvTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:AddUserInfo", RequestNamespace="http://axis2.fax.uniproud.com", ResponseNamespace="http://axis2.fax.uniproud.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public string AddUserInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string addUserStr) {
        object[] results = this.Invoke("AddUserInfo", new object[] {
                    addUserStr});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAddUserInfo(string addUserStr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AddUserInfo", new object[] {
                    addUserStr}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndAddUserInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void AddUserInfoAsync(string addUserStr) {
        this.AddUserInfoAsync(addUserStr, null);
    }
    
    /// <remarks/>
    public void AddUserInfoAsync(string addUserStr, object userState) {
        if ((this.AddUserInfoOperationCompleted == null)) {
            this.AddUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUserInfoOperationCompleted);
        }
        this.InvokeAsync("AddUserInfo", new object[] {
                    addUserStr}, this.AddUserInfoOperationCompleted, userState);
    }
    
    private void OnAddUserInfoOperationCompleted(object arg) {
        if ((this.AddUserInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AddUserInfoCompleted(this, new AddUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ChangePassword", RequestNamespace="http://axis2.fax.uniproud.com", ResponseNamespace="http://axis2.fax.uniproud.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public string ChangePassword([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string changePwdStr) {
        object[] results = this.Invoke("ChangePassword", new object[] {
                    changePwdStr});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginChangePassword(string changePwdStr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ChangePassword", new object[] {
                    changePwdStr}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndChangePassword(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ChangePasswordAsync(string changePwdStr) {
        this.ChangePasswordAsync(changePwdStr, null);
    }
    
    /// <remarks/>
    public void ChangePasswordAsync(string changePwdStr, object userState) {
        if ((this.ChangePasswordOperationCompleted == null)) {
            this.ChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePasswordOperationCompleted);
        }
        this.InvokeAsync("ChangePassword", new object[] {
                    changePwdStr}, this.ChangePasswordOperationCompleted, userState);
    }
    
    private void OnChangePasswordOperationCompleted(object arg) {
        if ((this.ChangePasswordCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ChangePasswordCompleted(this, new ChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:QueryResultForSendTask", RequestNamespace="http://axis2.fax.uniproud.com", ResponseNamespace="http://axis2.fax.uniproud.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public string QueryResultForSendTask([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string qrForSStr) {
        object[] results = this.Invoke("QueryResultForSendTask", new object[] {
                    qrForSStr});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginQueryResultForSendTask(string qrForSStr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("QueryResultForSendTask", new object[] {
                    qrForSStr}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndQueryResultForSendTask(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void QueryResultForSendTaskAsync(string qrForSStr) {
        this.QueryResultForSendTaskAsync(qrForSStr, null);
    }
    
    /// <remarks/>
    public void QueryResultForSendTaskAsync(string qrForSStr, object userState) {
        if ((this.QueryResultForSendTaskOperationCompleted == null)) {
            this.QueryResultForSendTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryResultForSendTaskOperationCompleted);
        }
        this.InvokeAsync("QueryResultForSendTask", new object[] {
                    qrForSStr}, this.QueryResultForSendTaskOperationCompleted, userState);
    }
    
    private void OnQueryResultForSendTaskOperationCompleted(object arg) {
        if ((this.QueryResultForSendTaskCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.QueryResultForSendTaskCompleted(this, new QueryResultForSendTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:QueryResultForRecvTask", RequestNamespace="http://axis2.fax.uniproud.com", ResponseNamespace="http://axis2.fax.uniproud.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public string QueryResultForRecvTask([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string qrForRStr) {
        object[] results = this.Invoke("QueryResultForRecvTask", new object[] {
                    qrForRStr});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginQueryResultForRecvTask(string qrForRStr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("QueryResultForRecvTask", new object[] {
                    qrForRStr}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndQueryResultForRecvTask(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void QueryResultForRecvTaskAsync(string qrForRStr) {
        this.QueryResultForRecvTaskAsync(qrForRStr, null);
    }
    
    /// <remarks/>
    public void QueryResultForRecvTaskAsync(string qrForRStr, object userState) {
        if ((this.QueryResultForRecvTaskOperationCompleted == null)) {
            this.QueryResultForRecvTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryResultForRecvTaskOperationCompleted);
        }
        this.InvokeAsync("QueryResultForRecvTask", new object[] {
                    qrForRStr}, this.QueryResultForRecvTaskOperationCompleted, userState);
    }
    
    private void OnQueryResultForRecvTaskOperationCompleted(object arg) {
        if ((this.QueryResultForRecvTaskCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.QueryResultForRecvTaskCompleted(this, new QueryResultForRecvTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:SendPHFaxToServer", RequestNamespace="http://axis2.fax.uniproud.com", ResponseNamespace="http://axis2.fax.uniproud.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public string SendPHFaxToServer([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sphfToXMLStr) {
        object[] results = this.Invoke("SendPHFaxToServer", new object[] {
                    sphfToXMLStr});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendPHFaxToServer(string sphfToXMLStr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendPHFaxToServer", new object[] {
                    sphfToXMLStr}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSendPHFaxToServer(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SendPHFaxToServerAsync(string sphfToXMLStr) {
        this.SendPHFaxToServerAsync(sphfToXMLStr, null);
    }
    
    /// <remarks/>
    public void SendPHFaxToServerAsync(string sphfToXMLStr, object userState) {
        if ((this.SendPHFaxToServerOperationCompleted == null)) {
            this.SendPHFaxToServerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendPHFaxToServerOperationCompleted);
        }
        this.InvokeAsync("SendPHFaxToServer", new object[] {
                    sphfToXMLStr}, this.SendPHFaxToServerOperationCompleted, userState);
    }
    
    private void OnSendPHFaxToServerOperationCompleted(object arg) {
        if ((this.SendPHFaxToServerCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendPHFaxToServerCompleted(this, new SendPHFaxToServerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:SendFaxToServer", RequestNamespace="http://axis2.fax.uniproud.com", ResponseNamespace="http://axis2.fax.uniproud.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public string SendFaxToServer([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sfToXMLStr) {
        object[] results = this.Invoke("SendFaxToServer", new object[] {
                    sfToXMLStr});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendFaxToServer(string sfToXMLStr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendFaxToServer", new object[] {
                    sfToXMLStr}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSendFaxToServer(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SendFaxToServerAsync(string sfToXMLStr) {
        this.SendFaxToServerAsync(sfToXMLStr, null);
    }
    
    /// <remarks/>
    public void SendFaxToServerAsync(string sfToXMLStr, object userState) {
        if ((this.SendFaxToServerOperationCompleted == null)) {
            this.SendFaxToServerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFaxToServerOperationCompleted);
        }
        this.InvokeAsync("SendFaxToServer", new object[] {
                    sfToXMLStr}, this.SendFaxToServerOperationCompleted, userState);
    }
    
    private void OnSendFaxToServerOperationCompleted(object arg) {
        if ((this.SendFaxToServerCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendFaxToServerCompleted(this, new SendFaxToServerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ModifyDeptInfo", RequestNamespace="http://axis2.fax.uniproud.com", ResponseNamespace="http://axis2.fax.uniproud.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public string ModifyDeptInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string modifyDeptStr) {
        object[] results = this.Invoke("ModifyDeptInfo", new object[] {
                    modifyDeptStr});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginModifyDeptInfo(string modifyDeptStr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ModifyDeptInfo", new object[] {
                    modifyDeptStr}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndModifyDeptInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ModifyDeptInfoAsync(string modifyDeptStr) {
        this.ModifyDeptInfoAsync(modifyDeptStr, null);
    }
    
    /// <remarks/>
    public void ModifyDeptInfoAsync(string modifyDeptStr, object userState) {
        if ((this.ModifyDeptInfoOperationCompleted == null)) {
            this.ModifyDeptInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyDeptInfoOperationCompleted);
        }
        this.InvokeAsync("ModifyDeptInfo", new object[] {
                    modifyDeptStr}, this.ModifyDeptInfoOperationCompleted, userState);
    }
    
    private void OnModifyDeptInfoOperationCompleted(object arg) {
        if ((this.ModifyDeptInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ModifyDeptInfoCompleted(this, new ModifyDeptInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:AddDeptInfo", RequestNamespace="http://axis2.fax.uniproud.com", ResponseNamespace="http://axis2.fax.uniproud.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public string AddDeptInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string addDeptStr) {
        object[] results = this.Invoke("AddDeptInfo", new object[] {
                    addDeptStr});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAddDeptInfo(string addDeptStr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AddDeptInfo", new object[] {
                    addDeptStr}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndAddDeptInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void AddDeptInfoAsync(string addDeptStr) {
        this.AddDeptInfoAsync(addDeptStr, null);
    }
    
    /// <remarks/>
    public void AddDeptInfoAsync(string addDeptStr, object userState) {
        if ((this.AddDeptInfoOperationCompleted == null)) {
            this.AddDeptInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddDeptInfoOperationCompleted);
        }
        this.InvokeAsync("AddDeptInfo", new object[] {
                    addDeptStr}, this.AddDeptInfoOperationCompleted, userState);
    }
    
    private void OnAddDeptInfoOperationCompleted(object arg) {
        if ((this.AddDeptInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AddDeptInfoCompleted(this, new AddDeptInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ModifyUserInfo", RequestNamespace="http://axis2.fax.uniproud.com", ResponseNamespace="http://axis2.fax.uniproud.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public string ModifyUserInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string modifyUIStr) {
        object[] results = this.Invoke("ModifyUserInfo", new object[] {
                    modifyUIStr});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginModifyUserInfo(string modifyUIStr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ModifyUserInfo", new object[] {
                    modifyUIStr}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndModifyUserInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ModifyUserInfoAsync(string modifyUIStr) {
        this.ModifyUserInfoAsync(modifyUIStr, null);
    }
    
    /// <remarks/>
    public void ModifyUserInfoAsync(string modifyUIStr, object userState) {
        if ((this.ModifyUserInfoOperationCompleted == null)) {
            this.ModifyUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyUserInfoOperationCompleted);
        }
        this.InvokeAsync("ModifyUserInfo", new object[] {
                    modifyUIStr}, this.ModifyUserInfoOperationCompleted, userState);
    }
    
    private void OnModifyUserInfoOperationCompleted(object arg) {
        if ((this.ModifyUserInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ModifyUserInfoCompleted(this, new ModifyUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetUserInfo", RequestNamespace="http://axis2.fax.uniproud.com", ResponseNamespace="http://axis2.fax.uniproud.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public string GetUserInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userInfoStr) {
        object[] results = this.Invoke("GetUserInfo", new object[] {
                    userInfoStr});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetUserInfo(string userInfoStr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetUserInfo", new object[] {
                    userInfoStr}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetUserInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetUserInfoAsync(string userInfoStr) {
        this.GetUserInfoAsync(userInfoStr, null);
    }
    
    /// <remarks/>
    public void GetUserInfoAsync(string userInfoStr, object userState) {
        if ((this.GetUserInfoOperationCompleted == null)) {
            this.GetUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoOperationCompleted);
        }
        this.InvokeAsync("GetUserInfo", new object[] {
                    userInfoStr}, this.GetUserInfoOperationCompleted, userState);
    }
    
    private void OnGetUserInfoOperationCompleted(object arg) {
        if ((this.GetUserInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetUserInfoCompleted(this, new GetUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:DeleteFileForSendTask", RequestNamespace="http://axis2.fax.uniproud.com", ResponseNamespace="http://axis2.fax.uniproud.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public string DeleteFileForSendTask([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string delForSTStr) {
        object[] results = this.Invoke("DeleteFileForSendTask", new object[] {
                    delForSTStr});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteFileForSendTask(string delForSTStr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteFileForSendTask", new object[] {
                    delForSTStr}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndDeleteFileForSendTask(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void DeleteFileForSendTaskAsync(string delForSTStr) {
        this.DeleteFileForSendTaskAsync(delForSTStr, null);
    }
    
    /// <remarks/>
    public void DeleteFileForSendTaskAsync(string delForSTStr, object userState) {
        if ((this.DeleteFileForSendTaskOperationCompleted == null)) {
            this.DeleteFileForSendTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFileForSendTaskOperationCompleted);
        }
        this.InvokeAsync("DeleteFileForSendTask", new object[] {
                    delForSTStr}, this.DeleteFileForSendTaskOperationCompleted, userState);
    }
    
    private void OnDeleteFileForSendTaskOperationCompleted(object arg) {
        if ((this.DeleteFileForSendTaskCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteFileForSendTaskCompleted(this, new DeleteFileForSendTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void QueryResultForRecvTaskZipCompletedEventHandler(object sender, QueryResultForRecvTaskZipCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class QueryResultForRecvTaskZipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal QueryResultForRecvTaskZipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void DeleteFileForRecvTaskCompletedEventHandler(object sender, DeleteFileForRecvTaskCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteFileForRecvTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeleteFileForRecvTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void AddUserInfoCompletedEventHandler(object sender, AddUserInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AddUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AddUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void ChangePasswordCompletedEventHandler(object sender, ChangePasswordCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void QueryResultForSendTaskCompletedEventHandler(object sender, QueryResultForSendTaskCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class QueryResultForSendTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal QueryResultForSendTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void QueryResultForRecvTaskCompletedEventHandler(object sender, QueryResultForRecvTaskCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class QueryResultForRecvTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal QueryResultForRecvTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void SendPHFaxToServerCompletedEventHandler(object sender, SendPHFaxToServerCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendPHFaxToServerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SendPHFaxToServerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void SendFaxToServerCompletedEventHandler(object sender, SendFaxToServerCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendFaxToServerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SendFaxToServerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void ModifyDeptInfoCompletedEventHandler(object sender, ModifyDeptInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ModifyDeptInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ModifyDeptInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void AddDeptInfoCompletedEventHandler(object sender, AddDeptInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AddDeptInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AddDeptInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void ModifyUserInfoCompletedEventHandler(object sender, ModifyUserInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ModifyUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ModifyUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetUserInfoCompletedEventHandler(object sender, GetUserInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void DeleteFileForSendTaskCompletedEventHandler(object sender, DeleteFileForSendTaskCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteFileForSendTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeleteFileForSendTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
