//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.42。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="IsmpSpEngineServiceSOAP11Binding", Namespace="http://sp.ismp.chinatelecom.com")]
public partial class IsmpSpEngineService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback orderRelationUpdateNotify1OperationCompleted;
    
    /// <remarks/>
    public IsmpSpEngineService() {
        this.Url = "http://localhost/servlet/services/IsmpSpEngineService";
    }
    
    /// <remarks/>
    public event orderRelationUpdateNotify1CompletedEventHandler orderRelationUpdateNotify1Completed;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:orderRelationUpdateNotify1", RequestNamespace="http://sp.ismp.chinatelecom.com", ResponseNamespace="http://sp.ismp.chinatelecom.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public NotifyManagementInfoRsp1 orderRelationUpdateNotify1([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] OrderRelationUpdateNotifyReq1 orderRelationUpdateNotifyReq) {
        object[] results = this.Invoke("orderRelationUpdateNotify1", new object[] {
                    orderRelationUpdateNotifyReq});
        return ((NotifyManagementInfoRsp1)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginorderRelationUpdateNotify1(OrderRelationUpdateNotifyReq1 orderRelationUpdateNotifyReq, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("orderRelationUpdateNotify1", new object[] {
                    orderRelationUpdateNotifyReq}, callback, asyncState);
    }
    
    /// <remarks/>
    public NotifyManagementInfoRsp1 EndorderRelationUpdateNotify1(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((NotifyManagementInfoRsp1)(results[0]));
    }
    
    /// <remarks/>
    public void orderRelationUpdateNotify1Async(OrderRelationUpdateNotifyReq1 orderRelationUpdateNotifyReq) {
        this.orderRelationUpdateNotify1Async(orderRelationUpdateNotifyReq, null);
    }
    
    /// <remarks/>
    public void orderRelationUpdateNotify1Async(OrderRelationUpdateNotifyReq1 orderRelationUpdateNotifyReq, object userState) {
        if ((this.orderRelationUpdateNotify1OperationCompleted == null)) {
            this.orderRelationUpdateNotify1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnorderRelationUpdateNotify1OperationCompleted);
        }
        this.InvokeAsync("orderRelationUpdateNotify1", new object[] {
                    orderRelationUpdateNotifyReq}, this.orderRelationUpdateNotify1OperationCompleted, userState);
    }
    
    private void OnorderRelationUpdateNotify1OperationCompleted(object arg) {
        if ((this.orderRelationUpdateNotify1Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.orderRelationUpdateNotify1Completed(this, new orderRelationUpdateNotify1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://req.sp.ismp.chinatelecom.com/xsd")]
public partial class OrderRelationUpdateNotifyReq1 {
    
    private int oPTypeField;
    
    private bool oPTypeFieldSpecified;
    
    private string packageIDField;
    
    private string productIDField;
    
    private string streamingNoField;
    
    private string userIDField;
    
    private int userIDTypeField;
    
    private bool userIDTypeFieldSpecified;
    
    /// <remarks/>
    public int oPType {
        get {
            return this.oPTypeField;
        }
        set {
            this.oPTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool oPTypeSpecified {
        get {
            return this.oPTypeFieldSpecified;
        }
        set {
            this.oPTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string packageID {
        get {
            return this.packageIDField;
        }
        set {
            this.packageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string productID {
        get {
            return this.productIDField;
        }
        set {
            this.productIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string streamingNo {
        get {
            return this.streamingNoField;
        }
        set {
            this.streamingNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string userID {
        get {
            return this.userIDField;
        }
        set {
            this.userIDField = value;
        }
    }
    
    /// <remarks/>
    public int userIDType {
        get {
            return this.userIDTypeField;
        }
        set {
            this.userIDTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool userIDTypeSpecified {
        get {
            return this.userIDTypeFieldSpecified;
        }
        set {
            this.userIDTypeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsp.sp.ismp.chinatelecom.com/xsd")]
public partial class NotifyManagementInfoRsp1 {
    
    private int resultCodeField;
    
    private bool resultCodeFieldSpecified;
    
    private string streamingNoField;
    
    /// <remarks/>
    public int resultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool resultCodeSpecified {
        get {
            return this.resultCodeFieldSpecified;
        }
        set {
            this.resultCodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string streamingNo {
        get {
            return this.streamingNoField;
        }
        set {
            this.streamingNoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void orderRelationUpdateNotify1CompletedEventHandler(object sender, orderRelationUpdateNotify1CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class orderRelationUpdateNotify1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal orderRelationUpdateNotify1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public NotifyManagementInfoRsp1 Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((NotifyManagementInfoRsp1)(this.results[0]));
        }
    }
}
