//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace HotelVp.Common.DataAccess
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.hotelvp.com/DataOperation")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.hotelvp.com/DataOperation", IsNullable = false)]
    public partial class dataOperations {
        
        private dataOperationsDataCommand[] dataCommandField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dataCommand")]
        public dataOperationsDataCommand[] dataCommand {
            get {
                return this.dataCommandField;
            }
            set {
                this.dataCommandField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hotelvp.com/DataOperation")]
    public partial class dataOperationsDataCommand {
        
        private string commandTextField;
        
        private dataOperationsDataCommandParameters parametersField;
        
        private string nameField;

        private string databaseField;
        
        private bool databaseFieldSpecified;
        
        private dataOperationsDataCommandCommandType commandTypeField;
        
        private int timeOutField;
        
        public dataOperationsDataCommand() {
            this.commandTypeField = dataOperationsDataCommandCommandType.Text;
            this.timeOutField = 300;
        }
        
        /// <remarks/>
        public string commandText {
            get {
                return this.commandTextField;
            }
            set {
                this.commandTextField = value;
            }
        }
        
        /// <remarks/>
        public dataOperationsDataCommandParameters parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string database
        {
            get {
                return this.databaseField;
            }
            set {
                this.databaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool databaseSpecified {
            get {
                return this.databaseFieldSpecified;
            }
            set {
                this.databaseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(dataOperationsDataCommandCommandType.Text)]
        public dataOperationsDataCommandCommandType commandType {
            get {
                return this.commandTypeField;
            }
            set {
                this.commandTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(300)]
        public int timeOut {
            get {
                return this.timeOutField;
            }
            set {
                this.timeOutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hotelvp.com/DataOperation")]
    public partial class dataOperationsDataCommandParameters {
        
        private dataOperationsDataCommandParametersParam[] paramField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("param")]
        public dataOperationsDataCommandParametersParam[] param {
            get {
                return this.paramField;
            }
            set {
                this.paramField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hotelvp.com/DataOperation")]
    public partial class dataOperationsDataCommandParametersParam {
        
        private string nameField;
        
        private dataOperationsDataCommandParametersParamDbType dbTypeField;
        
        private dataOperationsDataCommandParametersParamDirection directionField;
        
        private int sizeField;
        
        public dataOperationsDataCommandParametersParam() {
            this.directionField = dataOperationsDataCommandParametersParamDirection.Input;
            this.sizeField = -1;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dataOperationsDataCommandParametersParamDbType dbType {
            get {
                return this.dbTypeField;
            }
            set {
                this.dbTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(dataOperationsDataCommandParametersParamDirection.Input)]
        public dataOperationsDataCommandParametersParamDirection direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hotelvp.com/DataOperation")]
    public enum dataOperationsDataCommandParametersParamDbType {
        
        /// <remarks/>
        AnsiString,
        
        /// <remarks/>
        Binary,
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        Currency,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        Double,
        
        /// <remarks/>
        Int16,
        
        /// <remarks/>
        Int32,
        
        /// <remarks/>
        Int64,
        
        /// <remarks/>
        SByte,
        
        /// <remarks/>
        Single,
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        StringFixedLength,

        /// <remarks/>
        AnsiStringFixedLength,
        
        /// <remarks/>
        Time,
        
        /// <remarks/>
        UInt16,
        
        /// <remarks/>
        UInt32,
        
        /// <remarks/>
        UInt64,
        
        /// <remarks/>
        VarNumeric,
        
        /// <remarks/>
        Xml,
        /// <summary>
        /// 支持sql_variant 将使用SqlDbType对其参数设置
        /// </summary>
        Object,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hotelvp.com/DataOperation")]
    public enum dataOperationsDataCommandParametersParamDirection {
        
        /// <remarks/>
        Input,
        
        /// <remarks/>
        InputOutput,
        
        /// <remarks/>
        Output,
        
        /// <remarks/>
        ReturnValue,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hotelvp.com/DataOperation")]
    public enum dataOperationsDataCommandDatabase {
        
        /// <remarks/>
        Common,
        
        /// <remarks/>
        ControlPanel,
        
        /// <remarks/>
        ContentManagement,
        
        /// <remarks/>
        CustomerMasterProfile,
        
        /// <remarks/>
        InventoryManagement,
        
        /// <remarks/>
        InvoiceManagement,
        
        /// <remarks/>
        OrderManagement,
        
        /// <remarks/>
        POASNManagement,
        
        /// <remarks/>
        ServiceManagement,
        
        /// <remarks/>
        OZZO,
        
        /// <remarks/>
        OverseaLocalArchitecture,
        
        /// <remarks/>
        Portal,

        ServiceManagementSendSSB,

        ServiceManagementReceiveSSB,

        NEWSQL,

        D2WHP01,

        D2HIS01,

        EHISSQL,

        SSB,

        EIMSManagement,

    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hotelvp.com/DataOperation")]
    public enum dataOperationsDataCommandCommandType {
        
        /// <remarks/>
        StoredProcedure,
        
        /// <remarks/>
        TableDirect,
        
        /// <remarks/>
        Text,
    }
}
