ALTER TABLE T_LM_PROMOTION ADD PRIORITY  VARCHAR2(1); --优先级 1,2,3,4,5
ALTER TABLE T_LM_PROMOTION ADD PRO_IMAGE_ID VARCHAR2(100); --促销信息图片ID
ALTER TABLE T_LM_PROMOTION ADD STATUS VARCHAR2(1); --状态 0:下线 1:上线
ALTER TABLE T_LM_PROMOTION ADD USERGROUP VARCHAR2(1000);  --用户组
ALTER TABLE T_LM_PROMOTION ADD CITY_ID VARCHAR2(1000);  --城市
ALTER TABLE T_LM_PROMOTION ADD HOTELGROUP_ID VARCHAR2(1000);  --酒店集团
ALTER TABLE T_LM_PROMOTION ADD PROMOTIONMSG_ID VARCHAR2(1000);  --促销信息ID
--PRO_TYPE  促销类型 0:全局促销 1:城市促销 2:酒店集团促销 3:酒店促销 4:房型促销 5:用户组